CREATE TABLE pacientes (
    id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo_sangre VARCHAR2(3),
    telefono VARCHAR2(15),
    enfermedad VARCHAR2(100),
    numero_habitacion NUMBER,
    numero_cama NUMBER,
    fecha_nacimiento DATE
);

-- Creación de la tabla medicamentos
CREATE TABLE medicamentos (
    id_medicamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_medicamento VARCHAR2(100) NOT NULL,
    hora_aplicacion TIMESTAMP,
    id_paciente NUMBER,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente) ON DELETE CASCADE
);
